### ISSUE TITLE
Multiple Container bad calculation?

### ISSUE THREAD

**Issue by Franck31** [jmcgrath207/k8s-ephemeral-storage-metrics#103]
Hi,

I believe I've found an issue with our large cluster using a service mesh. In our setup, each pod contains four or more containers with the following ephemeral storage configurations:

```
Envy:
      limits:
        ephemeral-storage: 120Mi
      requests:
        ephemeral-storage: 100Mi
OpenTelemetry:
      limits:
        ephemeral-storage: 50Mi
      requests:
        ephemeral-storage: 50Mi
InjectorContainer:
      limits:
        ephemeral-storage: 300Mi
      requests:
        ephemeral-storage: 300Mi
ApplicationContainer:
      limits:
        ephemeral-storage: 5Mi
      requests:
        ephemeral-storage: 5Mi
```
        
 **Example:**

If the ApplicationContainer is using 1MB of its 5MB limit, the metric should ideally show:
        
`ephemeral_storage_container_limit_percentage{instance="10.1.1.1:9100", job="k8s-ephemeral-storage-metrics", node_name="ip-10-1-1-1.ec2.internal", pod_name="panchito-b5c46aed61caf53d3987832b-66b5b5b46d-29ntl", pod_namespace="sandbox-panchito",container="ApplicationContainer"} = 20`
        
However, because the exporter is using the 300MB limit from InjectorContainer and InjectorContainer is using 150MB, the metric inaccurately shows:
    
`ephemeral_storage_container_limit_percentage{instance="10.1.1.1:9100", job="k8s-ephemeral-storage-metrics", node_name="ip-10-1-1-1.ec2.internal", pod_name="panchito-b5c46aed61caf53d3987832b-66b5b5b46d-29ntl", pod_namespace="sandbox-panchito", container="ApplicationContainer"} = 3000`

This makes it impossible for us to use this metric as an alert to determine if a container is at risk of eviction.

Can this issue be addressed to correctly reflect the storage usage per container?
