### ISSUE TITLE
Update helm/template and values to make the metrics port configurable

### ISSUE THREAD

**Issue by odcheck** [jmcgrath207/k8s-ephemeral-storage-metrics#121]
Default node_exporter port is 9100 which will hammer it, if using also port 9100 for k8s-ephemeral-storage-metrics

like e.g.  in chart/templates/DeployType.yaml

```
      containers:
        - name: metrics
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.imagePullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          ports:
            - name: metrics
              containerPort: {{ .Values.metricsPort | default 9100 }}

          livenessProbe:
            failureThreshold: 10
            httpGet:
              path: /metrics
              port: {{ .Values.metricsPort | default 9100 }}
              
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /metrics
              port: {{ .Values.metricsPort | default 9100 }}
              scheme: HTTP              
```

and e.g. in metrics.yaml 

```
kind: Service
metadata:
  name: k8s-ephemeral-storage-metrics
  namespace: "{{ $.Release.Namespace }}"
  labels:
    {{- include "chart.labels" . | nindent 6 }}
spec:
  type: ClusterIP
  selector:
  {{- include "chart.selectorLabels" . | nindent 6 }}
  ports:
    - name: metrics
      port: {{ .Values.metricsPort | default 9100 }}
```

then it could be used in values like this e.g. 

```
image:
  repository: ghcr.io/jmcgrath207/k8s-ephemeral-storage-metrics
  tag: 1.13.0
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []

# -- Set port number for metrics port (default 9100)
metricsPort:
```
