### ISSUE TITLE
Suggestion: Add a "nodepool" or "agentpool" Label for Node Ephemeral Metrics

### ISSUE THREAD

**Issue by NoamVH** [jmcgrath207/k8s-ephemeral-storage-metrics#131]
I recently started using this exporter in my environment, however, I have a few issues and ideas with it. I will post them in seperate issues for your convenience.

The first one is that when using any of the `ephemeral_storage_node` metrics, I only get `node_name` as a label without `agentpool` or `nodepool`, so I can't easily differentiate between Kubernetes nodepools or use the `by` iterator in Grafana (avg by, sort by, etc.) or combine the metric with other metrics that relates to nodes.

Therefore, I think a `nodepool` or `agentpool` label (preferably `agentpool`) would be great.

**Comment by jmcgrath207** [comment]
Hi @NoamVH,

 I appreciate you breaking up these issues.
 
 I see your issue here, but I'm weary about adding extra labels for performance reasons. Also, `node pool` and `agent pool` are unique to environments. 
 
 I am open to adding a node filter by label. What do you think?
 
 ```
 kubectl get nodes minikube -o yaml
...
   labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: minikube
    kubernetes.io/os: linux
```
