### ISSUE TITLE
Bug(?): `ephemeral_storage_container_volume_usage` Shows the Wrong Volume

### ISSUE THREAD

**Issue by NoamVH** [jmcgrath207/k8s-ephemeral-storage-metrics#133]
When using the `ephemeral_storage_container_volume_usage` metric, I get a constant number, from what I'm seeing, there's a label `mount_path=/root/.config/app_config` that probably means that this is the mount that is being monitored, and I assume that the same mount is being monitored by `ephemeral_storage_container_volume_limit_percentage`.

I couldn't find any way to configure this differently, and there doesn't seem to be any documentation on the exporter except what little information is given in the `values.yaml` file.

Also, it seems like the correct volume is being monitored by `ephemeral_storage_container_limit_percentage` and `ephemeral_storage_pod_usage`, since they're showing correct results.

**Comment by jmcgrath207** [comment]
Hi @NoamVH,

`ephemeral_storage_container_volume_limit_percentage` uses a container's `sizeLimit` attribute from the pod spec and then divides that by the actual volume usage ( e.g., used volume bibytes / sizeLimit bibytes).  

For example, here is a test pod manifest, and notice the `sizeLimit` in the manifest.
https://github.com/jmcgrath207/k8s-ephemeral-storage-metrics/blob/master/chart/templates/test_deployments.yaml#L73

If that `sizeLimit` value is not defined, it will not be reported (see code below). This is why `ephemeral_storage_container_volume_limit_percentage` and `ephemeral_storage_container_volume_usage` behave differently.

https://github.com/jmcgrath207/k8s-ephemeral-storage-metrics/blob/master/pkg/pod/metrics.go#L148

I don't consider this a bug, but I agree that the documentation needs improvement. I will work on docs later this week.

**Comment by NoamVH** [comment]
Thank-you for the explanation, and thank-you for taking on improving the documentation, it's very important and will help future users, as well as save the need for you to answer issues like this.

I feel like maybe a naming convension for these two volume metrics could be modified in order for them to give a better clue on what they're doing, but honestly I can't really think of anything except maybe `ephemeral_storage_container_persistant_volumes_limit_percentage`, but that doesn't sound right. 😅

**Comment by jmcgrath207** [comment]
100% agree; I certainly "kicked the can" on this for a while since it's not the fun part :sweat_smile: . However, I have more time to improve this part of the project now than I did before.

> I feel like maybe the naming convension for these two volume metrics could be modified in order for them to give a better clue on what they're doing.

While I agree there could be improvement here, I would rather keep it so that user space remains intact. It's hard for me to know how others use this tool.

However, you can use the service monitor attributes here to relabel.
https://github.com/jmcgrath207/k8s-ephemeral-storage-metrics/blob/master/chart/values.yaml#L11-L19

**Comment by NoamVH** [comment]
This is a good idea, thank-you.

**Comment by NoamVH** [comment]
Greetings,

Took me a while to get there, for various reasons, but this is the configuration I made for changing the metrics' names:

```
metricRelabelings:
    - sourceLabels: [__name__]
      regex:  'ephemeral_storage_container_volume_usage'
      targetLabel: __name__
      replacement: 'ephemeral_storage_container_app_config_volume_usage_dont_use'
      action: replace
    - sourceLabels: [__name__]
      regex:  'ephemeral_storage_container_volume_limit_percentage'
      targetLabel: __name__
      replacement: 'ephemeral_storage_container_app_config_volume_usage_percentage_dont_use'
      action: replace
    - sourceLabels: [__name__]
      regex:  'ephemeral_storage_container_limit_percentage'
      targetLabel: __name__
      replacement: 'ephemeral_storage_container_usage_percentage'
      action: replace
    - sourceLabels: [__name__]
      regex:  'ephemeral_storage_pod_usage'
      targetLabel: __name__
      replacement: 'ephemeral_storage_pod_usage_bibytes'
      action: replace
    - sourceLabels: [__name__]
      regex:  'ephemeral_storage_node_available'
      targetLabel: __name__
      replacement: 'ephemeral_storage_node_available_bibytes'
      action: replace
    - sourceLabels: [__name__]
      regex:  'ephemeral_storage_node_capacity'
      targetLabel: __name__
      replacement: 'ephemeral_storage_node_capacity_bibytes'
      action: replace
    - sourceLabels: [__name__]
      regex:  'ephemeral_storage_node_percentage'
      targetLabel: __name__
      replacement: 'ephemeral_storage_node_usage_percentage_bibytes'
      action: replace
```

These modifications allow me to better recognize the metrics and what they do.

I'm leaving this snippet here for future reference by other people if they want to change the metrics names as well.

It should be also noted that the Prometheus Operator documentation links in the `serviceMonitor` section aren't leading anywhere.
I would also like to suggest leaving examples in comments in the code.

I will close this issue now, thank you again for your help.
