### ISSUE TITLE
Relabelings

### ISSUE THREAD

**Issue by mateuszdrab** [jmcgrath207/k8s-ephemeral-storage-metrics#74]
Hey

Just raising an idea that relabelings and metric relabelings should be configurable on the service monitor resource from the helm chart.

I need to relabel container and pod labels to match what kube state metrics provides.

**Comment by jmcgrath207** [comment]
Agree. I created a prerelease, `1.6.3-rc01,` for you to test my changes.  

https://github.com/jmcgrath207/k8s-ephemeral-storage-metrics/releases/tag/1.6.3-rc01

The changes I made are in https://github.com/jmcgrath207/k8s-ephemeral-storage-metrics/pull/76, which works with empty values. 

Admittedly, I am not super familiar with this. If your change works, could you send me a test case? I want to add it to our e2e tests.

Thanks!

**Comment by mateuszdrab** [comment]
Thanks for implementing the change so quickly.

I'm trying to deploy the chart with the below values but there's an error, think it might be an indentation issue.
`Error: UPGRADE FAILED: YAML parse error on k8s-ephemeral-storage-metrics/templates/metrics.yaml: error converting YAML to JSON: yaml: line 16: did not find expected key`

```
serviceMonitor:
  relabelings:
    - sourceLabels: [pod_name]
      targetLabel: pod
    - sourceLabels: [pod_namespace]
      targetLabel: namespace
    # drop labels pod_.*
    - regex: "pod_(.*)"
      action: labeldrop
```
