### ISSUE TITLE
ephemeral_storage_pod_usage  Can empty directory memory be supported?

### ISSUE THREAD

**Issue by jicki** [jmcgrath207/k8s-ephemeral-storage-metrics#85]
`ephemeral_storage_pod_usage`.  Can empty directory memory be supported?

```
  volumes:
  - name: cache-volume
    emptyDir:
      medium: Memory
      sizeLimit: 500Mi
```
